#### 1. Import the numpy package under the name `np`

#### Import արեք numpy module-ը np անունով:

In [1]:
import numpy as np

#### 2. Create a numpy array of size 10 filled with zeros. 

#### Ստեղծեք 10 չափի 0-ներով լցված numpy array:

In [3]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3.  How to get the documentation of the numpy add function? 

#### Նայեք numpy-ի add ֆունկցիայի դոկումենտացիան:

In [4]:
?np.add

#### 4.  Create a numpy array of size 10 filled with zeros but the fifth value is 1 

#### Ստեղծեք 10 չափի 0-ներով լցված numpy array, որի 5րդ արժեքը 1 է:

In [7]:
arr[4] = 1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 5.  Create a numpy array with values ranging from 10 to 49

#### Ստեղծեք 10-ից 49 հաջորդական թվերով numpy array:

In [10]:
new_arr = np.arange(10,50)
new_arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 6.  Reverse the numpy array ranging from 0 to 50. 

#### Ստեղծեք 0-ից 50 հաջորդական թվերով numpy array և տպեք այն շրջած ձևով:

In [15]:
arr = np.arange(10,51)
print(np.flip(arr))

[50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 7.  Create a 3x3 matrix with values ranging from 0 to 8 

#### Ստեղծեք 0-ից 8 հաջորդական թվերով 3x3 numpy array

In [21]:
arr = np.arange(9)
my_arr = arr.reshape(3,3)
my_arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 8. Find indices of non-zero elements from \[1,2,0,0,4,0\]

#### Տրված է \[1,2,0,0,4,0\] numpy array-ը, գտեք ոչ-զրոյական արժեքներով տարրերի ինդեքսները:

In [31]:
a = np.array([1,2,0,0,4,0])
list1 = []
for i in range(0,len(a)):
    if a[i] != 0:
        list1.append(i)
print(list1)


[0, 1, 4]


#### 9. Create a 3x3x3 array with random integers from 1 to 20

#### Ստեղծեք 1-ից 20 պատահական թվերով լցված (3x3x3) չափանի numpy array:

In [32]:
np.random.randint(size = (3,3,3), low = 1, high = 20)

array([[[ 8, 12,  6],
        [19,  2, 19],
        [ 4, 19, 10]],

       [[ 1, 16,  2],
        [16, 11,  3],
        [ 5,  6, 10]],

       [[19,  7, 11],
        [12,  8,  3],
        [14,  9,  4]]])

#### 10. Create a 10x10 array with random values and find the minimum and maximum values 

#### Ստեղծեք պատահական թվերով լցված (10x10) չափանի numpy array ու տպեք դրա փոքրագույն ու մեծագույն արժեքները:

In [66]:
my_numpy_array = np.random.randint(size = (10,10), low = 1, high = 1000)
print(np.amin(my_numpy_array))
print(np.amax(my_numpy_array))

4
999


#### 11. Create a random vector of size 30 and find the mean value 

#### Ստեղծեք 30 չափանի պատահական թվերով լցված numpy array ու տպեք դրա միջին արժեքը:

In [69]:
rand = np.random.randn(30)
np.mean(rand)

-0.1419347241042725

#### 12. Given a 1D array ranging from 0 to 10, print all the elements which are between 3 and 8. 

#### Ստեղծեք 0-ից 10 հաջորդական թվերով numpy array: Տպեք բոլոր արժեքները, որոնք 3-ից 8 միջակայքում են:

In [75]:
seq = np.arange(11)
seq[(seq >3) & (seq<8)]

array([4, 5, 6, 7])

#### 13. Given a 1D array of 20 random integers from 0 to 10, multiply the values that are less than 5 by 2 and print the resulting array.

#### Ստեղծեք 1-ից 10 պատահական ամբողջ թվերով լցված 20 չափանի numpy array: Բազմապատկեք 5-ից փոքր արժեք ունեցող տարերրը 2-ով ու տպեք արդյունքում ստացված array-ը:

In [87]:
array = np.random.randint(size = 20, low = 0, high = 11)
new_arr = array[array < 5] *2 
new_arr

array([8, 0, 6, 6, 4, 8, 6, 4, 8])

#### 14. Given the 1D array [1, 5, 6, 2, -2, 23, 45], find the indices of the array elements that are divisible by 2.

#### Տրված է [1, 5, 6, 2, -2, 23, 45] numpy array-ը, գտեք 2-ի բաժանվող տարրերի կոորդինատները:

In [89]:
given = np.array([1,5,6,2,-2,23,45])
new_list = []
for i in range(0,len(given)):
    if given[i] % 2 == 0:
        new_list.append(i)
print(new_list)

[2, 3, 4]


#### 15. Given a 1D array ranging from 0 to 20, print all the elements which are divisible by 3. 

#### Ստեղծեք 1-ից 20 հաջորդական թվերով լցված numpy array, տպեք բոլոր 3-ի բաժանվող տարրերի արժեքները:

In [94]:
a = np.arange(1,21)
print(a[a % 3 == 0])

[ 3  6  9 12 15 18]


#### 16. Create a 5x5 numpy array with each row values ranging from 0 to 4 

#### Ստեղծեք 5x5 numpy array, որի ամեն տող իրենից ներկայացնում է 0-ից 4 հաջորդական թվեր:

In [101]:
x = np.zeros((5,5))
x += np.arange(5)
x

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 17. Create the following 2x2 numpy array np.array([[0, 1],[2, 3]]). Find the minimum and maximum values in the array.

#### Ստեղծեք 2x2 numpy array np.array([[0, 1],[2, 3]]) : Գտեք array-ի մեծագույն ու փոքրագույն արժեքները։

In [109]:
num_array = np.array([[0,1],[2,3]])
print(np.amin(num_array))
print(np.amax(num_array))

0
3


#### 18. Create the following 2x2 numpy array np.array([[0, 1],[2, 3]]). Find the minimum and maximum values in each column.

#### Ստեղծեք 2x2 numpy array np.array([[0, 1],[2, 3]]) : Գտեք array-ի սյուների մեծագույն ու փոքրագույն արժեքները։

In [117]:
num_array = np.array([[0,1],[2,3]])
print(np.amin(num_array, axis = 0))
print(np.amax(num_array, axis = 0))

[0 1]
[2 3]


#### 19. Create  numpy array of size 10 filled with integers of your choice. Compute mean, median, standard deviation and variance of the array values. 

#### Ստեղծեք 10 չափանի numpy array, հաշվեք array-ի mean, median, standard deviation և variance։

In [133]:
myArray = np.array([1,2,4,5,6,5,7,8,4,23])
print(np.mean(myArray))
print(np.median(myArray))
print(np.std(myArray))
print(np.var(myArray))


6.5
5.0
5.852349955359813
34.25


#### 20. Calculate the weighted average of the following array: np.array([2, 4, 3, 5, 6, 12, 34, 2, 34, 5]) using weights np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]). 

#### Հաշվեք տրված array-ի կշռված միջինը՝ np.array([2, 4, 3, 5, 6, 12, 34, 2, 34, 5])` օգտագործելով np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) weight-երը։

In [136]:
x1 = np.array([2, 4, 3, 5, 6, 12, 34, 2, 34, 5]) 
weights = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(sum(weights * x1)/sum(weights))

13.654545454545454


#### 21. Sort the rows of the following numpy array in an increasing order: np.array([[4, 2, 6, 1],[0, 2, 6, 1],[4, 4, 1, 9]]). 

#### Աճման կարգով դասավորեք տրված numpy array-ի տողերը՝ np.array([[4, 2, 6, 1],[0, 2, 6, 1],[4, 4, 1, 9]]):

In [140]:
arr1 =  np.array([[4, 2, 6, 1],[0, 2, 6, 1],[4, 4, 1, 9]])
print(arr1)
print("\n")
print(np.sort(arr1, axis =1))

[[4 2 6 1]
 [0 2 6 1]
 [4 4 1 9]]


[[1 2 4 6]
 [0 1 2 6]
 [1 4 4 9]]


#### 22. Create the following numpy arrays and calculate the dot product between a and b. 

#### Ստեղծեք հետևյալ numpy array-ները ու հաշվեք a և b array-ների dot product-ը։

$$a = \begin{bmatrix} 3 & 6 & 7 \\ 5 & -3 & 0  \end{bmatrix}$$

$$b = \begin{bmatrix} 1 & 1 \\ 2 & 1 \\ 3 & -3 \end{bmatrix}$$

In [142]:
a = np.array([[3,6,7],[5,-3,0]])
b = np.array([[1,1],[2,1],[3,-3]])
print(a.dot(b))

[[ 36 -12]
 [ -1   2]]
